Traceback (most recent call last):
  File "c:\Users\delan\OneDrive\Desktop\PyomoGallery\abdelaneverisons\pyomogallery\.venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\Users\delan\OneDrive\Desktop\PyomoGallery\abdelaneverisons\pyomogallery\.venv\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\Users\delan\OneDrive\Desktop\PyomoGallery\abdelaneverisons\pyomogallery\.venv\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\Users\delan\OneDrive\Desktop\PyomoGallery\abdelaneverisons\pyomogallery\.venv\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "c:\Users\delan\OneDrive\Desktop\PyomoGallery\abdelaneverisons\pyomogallery\.venv\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\Users\delan\OneDrive\Desktop\PyomoGallery\abdelaneverisons\pyomogallery\.venv\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pyomo.environ as pyo
#imports pyomo package
infinity = float('inf')
#sets infinity to a float value

model = pyo.AbstractModel()
#creates an abstract model named model
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[2], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpyomo[39;00m[38;5;21;01m.[39;00m[38;5;21;01menviron[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpyo[39;00m
[0;32m      2[0m [38;5;66;03m#imports pyomo package[39;00m
[0;32m      3[0m infinity [38;5;241m=[39m [38;5;28mfloat[39m([38;5;124m'[39m[38;5;124minf[39m[38;5;124m'[39m)

[1;31mModuleNotFoundError[0m: No module named 'pyomo'

